# Generated by Django 3.1.6 on 2021-02-16 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210217_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_user',
            new_name='user',
        ),
    ]
