# Generated by Django 3.1.6 on 2021-02-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210217_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
