# Generated by Django 3.1.6 on 2021-02-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_user_profile'),
        ('blog', '0006_auto_20210217_1632'),
    ]

    operations = [
    ]
